# Generated by Django 3.2.4 on 2021-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210703_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='meals',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
