# Generated by Django 3.2.4 on 2021-07-03 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20210703_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='target',
        ),
        migrations.AlterField(
            model_name='data',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='meals',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='DataTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
